In [27]:
import requests as re
import pandas as pd
import numpy as np
import json
import math
from pandas.io.json import json_normalize
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
from sklearn.externals import joblib
from sklearn.cluster import DBSCAN

# New kmeans

In [54]:
raw = pd.read_csv('line.csv')
df_loc = raw[['latitude', 'longitude','property_type']]

In [55]:
df_loc = pd.get_dummies(df_loc)

In [56]:
loc = np.array(df_loc)

scaler = StandardScaler()
StandardScaler(copy=True, with_mean=True, with_std=True)

scaler.fit(loc)
X = scaler.transform(loc)


# k_model = KMeans()
# k_model.fit(loc)
# y_pred = k_model.predict(loc)

db_model = DBSCAN(eps = 0.1, min_samples = 10)
y_pred = db_model.fit_predict(loc)

df_loc['class'] = y_pred
df_loc.groupby('class').count()
#joblib.dump(k_model, "k_model2.m")

,latitude,longitude,property_type_Barn conversion,property_type_Block of flats,property_type_Bungalow,property_type_Chalet,property_type_Cottage,property_type_Country house,property_type_Detached bungalow,property_type_Detached house,...,property_type_Mews house,property_type_Mobile/park home,property_type_Parking/garage,property_type_Semi-detached bungalow,property_type_Semi-detached house,property_type_Studio,property_type_Terraced bungalow,property_type_Terraced house,property_type_Town house,property_type_Villa
class,,,,,,,,,,,,,,,,,,,,,
-1,392,392,392,392,392,392,392,392,392,392,...,392,392,392,392,392,392,392,392,392,392
0,573,573,573,573,573,573,573,573,573,573,...,573,573,573,573,573,573,573,573,573,573
1,1426,1426,1426,1426,1426,1426,1426,1426,1426,1426,...,1426,1426,1426,1426,1426,1426,1426,1426,1426,1426
2,332,332,332,332,332,332,332,332,332,332,...,332,332,332,332,332,332,332,332,332,332
3,709,709,709,709,709,709,709,709,709,709,...,709,709,709,709,709,709,709,709,709,709
4,1152,1152,1152,1152,1152,1152,1152,1152,1152,1152,...,1152,1152,1152,1152,1152,1152,1152,1152,1152,1152
5,253,253,253,253,253,253,253,253,253,253,...,253,253,253,253,253,253,253,253,253,253
6,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
7,57,57,57,57,57,57,57,57,57,57,...,57,57,57,57,57,57,57,57,57,57
8,257,257,257,257,257,257,257,257,257,257,...,257,257,257,257,257,257,257,257,257,257
9,22,22,22,22,22,22,22,22,22,22,...,22,22,22,22,22,22,22,22,22,22
10,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
11,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
12,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
13,57,57,57,57,57,57,57,57,57,57,...,57,57,57,57,57,57,57,57,57,57
14,45,45,45,45,45,45,45,45,45,45,...,45,45,45,45,45,45,45,45,45,45
15,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
16,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,29,29
17,39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,39,39,39,39,39
18,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13
19,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
20,26,26,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,26,26,26
21,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
22,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
23,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19
24,39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,39,39,39,39,39
25,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
26,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
27,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
28,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
29,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11

In [57]:
raw['loc_class'] = y_pred
df_line_regression = raw[['latitude','longitude','property_type', 'num_bathrooms', 'num_bedrooms','num_floors', 'num_recepts', 'new_home', 'loc_class', 'price']]

In [58]:
df_line_regression.to_csv('second.csv')

# Data preprocessing